spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca?useTimezone=true&serverTimezone=UTC
    username: root
    password: 4321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: trueUNIQUE (name)
        dialect: org.hibernate.dialect.MySQL8Dialect
